### ISSUE TITLE
cellpose script not working

### ISSUE THREAD

**Issue by pwalczysko** [ome/EMBL-EBI-imaging-course-05-2023#14]
```
(imaging_course_cellpose_day4_2023) pwalczysko@Petrs-MBP Day_4 % python scripts/cellpose.py 
Traceback (most recent call last):
  File "/Users/pwalczysko/Work/EMBL-EBI-imaging-course-05-2023/Day_4/scripts/cellpose.py", line 52, in <module>
    from cellpose import io, models, utils
  File "/Users/pwalczysko/Work/EMBL-EBI-imaging-course-05-2023/Day_4/scripts/cellpose.py", line 52, in <module>
    from cellpose import io, models, utils
ImportError: cannot import name 'io' from partially initialized module 'cellpose' (most likely due to a circular import) (/Users/pwalczysko/Work/EMBL-EBI-imaging-course-05-2023/Day_4/scripts/cellpose.py)
```

**Comment by jburel** [comment]
Strange I did not have the issue. I will try again

**Comment by pwalczysko** [comment]
@jburel I have a solution

```
(imaging_course_cellpose_day4_2023) pwalczysko@Petrs-MBP EMBL-EBI-imaging-course-05-2023 % mv Day_4/scripts/cellpose.py Day_4/scripts/cellpose1.py
(imaging_course_cellpose_day4_2023) pwalczysko@Petrs-MBP EMBL-EBI-imaging-course-05-2023 % 
(imaging_course_cellpose_day4_2023) pwalczysko@Petrs-MBP EMBL-EBI-imaging-course-05-2023 % 
(imaging_course_cellpose_day4_2023) pwalczysko@Petrs-MBP EMBL-EBI-imaging-course-05-2023 % python Day_4/scripts/cellpose1.py                      
Connected: True
t:1 c:2 z:257 y:210 x:253
Downloading image B4_C3.tif
...
```

According to the https://stackoverflow.com/questions/64807163/importerror-cannot-import-name-from-partially-initialized-module-m , it is connected with naming the script with the same name as a package. 
Indeed, when I renamed the script ^^^, it started to work

**Comment by pwalczysko** [comment]
But then it crashes on another error

```
Traceback (most recent call last):
  File "/Users/pwalczysko/Work/EMBL-EBI-imaging-course-05-2023/Day_4/scripts/cellpose1.py", line 194, in <module>
    main()
  File "/Users/pwalczysko/Work/EMBL-EBI-imaging-course-05-2023/Day_4/scripts/cellpose1.py", line 182, in main
    save_labels_as_geojson(gc, image_id)
NameError: name 'save_labels_as_geojson' is not defined
```

**Comment by jburel** [comment]
ok thanks I will change the script name and fix the issue

**Comment by jburel** [comment]
pushed. The problem should be sorted

**Comment by pwalczysko** [comment]
confirming the fix
